export enum SectorEconomico {
  COMERCIO_SERVICIOS_INDUSTRIA = 'COMERCIO_SERVICIOS_INDUSTRIA',
  MAQUILA_TEXTIL = 'MAQUILA_TEXTIL',
  BENEFICIOS_CAFE_AZUCAR = 'BENEFICIOS_CAFE_AZUCAR',
  AGROPECUARIO = 'AGROPECUARIO',
}

export const SALARIO_MINIMO_SECTOR = {
  [SectorEconomico.COMERCIO_SERVICIOS_INDUSTRIA]: 408.8,
  [SectorEconomico.MAQUILA_TEXTIL]: 402.32,
  [SectorEconomico.BENEFICIOS_CAFE_AZUCAR]: 305.23,
  [SectorEconomico.AGROPECUARIO]: 272.53,
};
