export enum TipoNovedad {
  HORAS_EXTRA = 'HORAS_EXTRA',
  PERMISO_SIN_GOCE = 'PERMISO_SIN_GOCE',
  BONIFICACION = 'BONIFICACION',
  DESCUENTO = 'DESCUENTO',
  LICENCIA_MATERNIDAD = 'LICENCIA_MATERNIDAD',
}
